# Generated by Django 5.0.3 on 2024-03-19 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studenthousing", "0002_userquery_delete_house_delete_studentprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="Listing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("price_range", models.CharField(max_length=100)),
                ("bedrooms", models.CharField(max_length=10)),
                ("bathrooms", models.CharField(max_length=10)),
            ],
        ),
    ]
