# Generated by Django 5.0.3 on 2024-04-11 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studenthousing", "0003_listing"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApartmentListings",
            fields=[
                ("listing_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(max_length=3)),
                ("address", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("zip_code", models.CharField(max_length=20)),
                ("country", models.CharField(max_length=100)),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("bedrooms", models.IntegerField()),
                ("bathrooms", models.DecimalField(decimal_places=1, max_digits=3)),
                ("area", models.IntegerField()),
                ("unit_type", models.CharField(max_length=50)),
                ("floor_number", models.IntegerField(blank=True, null=True)),
                ("total_floors", models.IntegerField(blank=True, null=True)),
                ("heating", models.BooleanField()),
                ("cooling", models.BooleanField()),
                ("balcony", models.BooleanField()),
                ("furnished", models.BooleanField()),
                ("pet_friendly", models.BooleanField()),
                ("parking", models.CharField(max_length=100)),
                ("laundry", models.CharField(max_length=100)),
                ("utilities_included", models.CharField(max_length=255)),
                ("deposit", models.DecimalField(decimal_places=2, max_digits=10)),
                ("lease_length", models.CharField(max_length=50)),
                ("availability_date", models.DateField()),
                ("last_updated", models.DateTimeField()),
                ("owner_id", models.IntegerField()),
                ("status", models.CharField(max_length=50)),
                ("created_by", models.IntegerField()),
                ("created_date", models.DateTimeField()),
                ("modified_by", models.IntegerField(blank=True, null=True)),
                ("modified_date", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
