# Generated by Django 5.0.3 on 2024-04-28 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studenthousing", "0004_apartmentlistings"),
    ]

    operations = [
        migrations.AddField(
            model_name="apartmentlistings",
            name="is_shared",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="apartmentlistings",
            name="max_occupancy",
            field=models.IntegerField(default=1),
        ),
    ]
