# Generated by Django 5.0.3 on 2024-05-02 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studenthousing", "0005_apartmentlistings_is_shared_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="apartmentlistings",
            old_name="max_occupancy",
            new_name="current_tenants",
        ),
        migrations.AddField(
            model_name="apartmentlistings",
            name="total_tenants",
            field=models.IntegerField(default=1),
        ),
    ]
